version: "3.8"

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    env_file: ./backend/.env
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  frontoffice:
    build: ./frontoffice
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backoffice:
    build: ./backoffice
    ports:
      - "3001:3000"
    depends_on:
      - backend

volumes:
  mongo-data:
