services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: ./backend/.env
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - mongo

  frontoffice:
    build:
      context: ./frontoffice
      dockerfile: Dockerfile
    ports:
      - "3000:3000"   # CRA React utilise 3000
    volumes:
      - ./frontoffice:/app
      - /app/node_modules
    command: npm start
    depends_on:
      - backend

  backoffice:
    build:
      context: ./backoffice
      dockerfile: Dockerfile
    ports:
      - "5174:5174"   # si Vite, c’est bon
    volumes:
      - ./backoffice:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - backend

volumes:
  mongo-data:
